export type GalleryCategory =
    | "Wildlife"
    | "Landscapes"
    | "Cultural"
    | "Adventure"
    | "Accommodations";

export interface GalleryImage {
    id: number;
    src: string;
    alt: string;
    categories: GalleryCategory[];
    caption: string;
    location?: string;
    featured: boolean;
    /** "landscape" | "portrait" | "square" — drives masonry row-span */
    aspectRatio: "landscape" | "portrait" | "square";
}

export const galleryCategories: GalleryCategory[] = [
    "Wildlife",
    "Landscapes",
    "Cultural",
    "Adventure",
    "Accommodations",
];

/**
 * 32 curated Unsplash images organised by safari category.
 * All URLs use ?w=800&q=80 for the grid; the lightbox can swap to larger sizes at runtime.
 */
export const galleryImages: GalleryImage[] = [
    // ── Wildlife ──────────────────────────────────────────
    {
        id: 1,
        src: "https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800&q=80",
        alt: "Male lion resting in golden grassland",
        categories: ["Wildlife"],
        caption: "King of the savanna — a male lion surveys his territory at dawn.",
        location: "Hwange National Park",
        featured: true,
        aspectRatio: "landscape",
    },
    {
        id: 2,
        src: "https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800&q=80",
        alt: "Elephant herd at a watering hole",
        categories: ["Wildlife"],
        caption: "An elephant family gathers at the river during the dry season.",
        location: "Mana Pools",
        featured: true,
        aspectRatio: "portrait",
    },
    {
        id: 3,
        src: "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=800&q=80",
        alt: "Leopard on a tree branch",
        categories: ["Wildlife"],
        caption: "A leopard watches from its vantage point high in a marula tree.",
        location: "Hwange National Park",
        featured: false,
        aspectRatio: "portrait",
    },
    {
        id: 4,
        src: "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=800&q=80",
        alt: "Giraffe silhouette at sunset",
        categories: ["Wildlife", "Landscapes"],
        caption: "Giraffes framed against a fiery African sunset.",
        location: "Zambezi Valley",
        featured: true,
        aspectRatio: "landscape",
    },
    {
        id: 5,
        src: "https://images.unsplash.com/photo-1557050543-4d5f4e07ef46?w=800&q=80",
        alt: "African wild dogs hunting",
        categories: ["Wildlife"],
        caption: "Painted wolves — Africa's most efficient predators on the move.",
        location: "Mana Pools",
        featured: true,
        aspectRatio: "landscape",
    },
    {
        id: 6,
        src: "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=800&q=80",
        alt: "Zebras at waterhole",
        categories: ["Wildlife"],
        caption: "A dazzle of zebras reflected in still waters.",
        location: "Hwange National Park",
        featured: false,
        aspectRatio: "square",
    },
    {
        id: 7,
        src: "https://images.unsplash.com/photo-1549366021-9f761d450615?w=800&q=80",
        alt: "Rhino mother and calf",
        categories: ["Wildlife"],
        caption: "A rare sighting — a white rhino mother and calf in the early morning mist.",
        location: "Matobo Hills",
        featured: false,
        aspectRatio: "landscape",
    },
    {
        id: 8,
        src: "https://images.unsplash.com/photo-1518709766631-a6a7f45921c3?w=800&q=80",
        alt: "Hippos in the Zambezi River",
        categories: ["Wildlife"],
        caption: "Hippos cool off in the powerful currents of the Zambezi.",
        location: "Zambezi River",
        featured: false,
        aspectRatio: "landscape",
    },

    // ── Landscapes ────────────────────────────────────────
    {
        id: 9,
        src: "https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800&q=80",
        alt: "African savanna at golden hour",
        categories: ["Landscapes"],
        caption: "Endless golden plains stretch beneath a dramatic African sky.",
        location: "Hwange National Park",
        featured: true,
        aspectRatio: "landscape",
    },
    {
        id: 10,
        src: "https://images.unsplash.com/photo-1489392191049-fc10c97e64b6?w=800&q=80",
        alt: "Victoria Falls panoramic view",
        categories: ["Landscapes", "Adventure"],
        caption: "The Smoke that Thunders — Victoria Falls in full flood.",
        location: "Victoria Falls",
        featured: true,
        aspectRatio: "portrait",
    },
    {
        id: 11,
        src: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
        alt: "Sunrise over misty valley",
        categories: ["Landscapes"],
        caption: "Dawn breaks over the misty valleys of the Eastern Highlands.",
        location: "Eastern Highlands",
        featured: false,
        aspectRatio: "landscape",
    },
    {
        id: 12,
        src: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e?w=800&q=80",
        alt: "Acacia tree silhouette",
        categories: ["Landscapes"],
        caption: "The iconic silhouette of an acacia tree against a painted sky.",
        location: "Hwange National Park",
        featured: false,
        aspectRatio: "square",
    },
    {
        id: 13,
        src: "https://images.unsplash.com/photo-1500534623283-312aade485b7?w=800&q=80",
        alt: "Starry night over savanna",
        categories: ["Landscapes"],
        caption: "The Milky Way arches over the African bush — zero light pollution.",
        location: "Hwange National Park",
        featured: false,
        aspectRatio: "landscape",
    },
    {
        id: 14,
        src: "https://images.unsplash.com/photo-1612528443702-f6741f70a049?w=800&q=80",
        alt: "Baobab tree at sunset",
        categories: ["Landscapes"],
        caption: "Ancient baobabs stand sentinel over the changing seasons.",
        location: "Gonarezhou National Park",
        featured: false,
        aspectRatio: "portrait",
    },

    // ── Cultural ──────────────────────────────────────────
    {
        id: 15,
        src: "https://images.unsplash.com/photo-1523805009345-7448845a9e53?w=800&q=80",
        alt: "Traditional village scene",
        categories: ["Cultural"],
        caption: "Sharing stories and traditions with the local community.",
        location: "Masvingo Province",
        featured: true,
        aspectRatio: "landscape",
    },
    {
        id: 16,
        src: "https://images.unsplash.com/photo-1504432842672-1a79f78e4084?w=800&q=80",
        alt: "Traditional dancers performing",
        categories: ["Cultural"],
        caption: "Vibrant traditional dances celebrate centuries-old heritage.",
        location: "Victoria Falls Village",
        featured: false,
        aspectRatio: "square",
    },
    {
        id: 17,
        src: "https://images.unsplash.com/photo-1590845947698-dc1d35fda8e2?w=800&q=80",
        alt: "Local artisan crafting",
        categories: ["Cultural"],
        caption: "Skilled artisans create beautiful sculptures from local stone.",
        location: "Tengenenge",
        featured: false,
        aspectRatio: "portrait",
    },
    {
        id: 18,
        src: "https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=800&q=80",
        alt: "Traditional basket weaving",
        categories: ["Cultural"],
        caption: "The intricate art of basket weaving passed down through generations.",
        location: "Binga",
        featured: false,
        aspectRatio: "landscape",
    },

    // ── Adventure ─────────────────────────────────────────
    {
        id: 19,
        src: "https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800&q=80",
        alt: "Safari vehicle at sunrise",
        categories: ["Adventure"],
        caption: "The adventure begins — setting out on an early morning game drive.",
        location: "Hwange National Park",
        featured: true,
        aspectRatio: "landscape",
    },
    {
        id: 20,
        src: "https://images.unsplash.com/photo-1551524164-687a55dd1126?w=800&q=80",
        alt: "Canoe safari on the Zambezi",
        categories: ["Adventure"],
        caption: "Paddling silently past hippos and crocs on a canoe safari.",
        location: "Mana Pools",
        featured: false,
        aspectRatio: "landscape",
    },
    {
        id: 21,
        src: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80",
        alt: "Walking safari guide with guests",
        categories: ["Adventure"],
        caption: "Up close and personal — a guided walking safari through the bush.",
        location: "Mana Pools",
        featured: false,
        aspectRatio: "portrait",
    },
    {
        id: 22,
        src: "https://images.unsplash.com/photo-1530789253388-582c481c54b0?w=800&q=80",
        alt: "Bungee jumping at Victoria Falls Bridge",
        categories: ["Adventure"],
        caption: "The ultimate thrill — 111m bungee jump over the Zambezi gorge.",
        location: "Victoria Falls Bridge",
        featured: false,
        aspectRatio: "portrait",
    },
    {
        id: 23,
        src: "https://images.unsplash.com/photo-1528543606781-2f6e6857f318?w=800&q=80",
        alt: "Hot air balloon over savanna",
        categories: ["Adventure", "Landscapes"],
        caption: "A breathtaking bird's-eye view from a hot air balloon at sunrise.",
        location: "Hwange National Park",
        featured: false,
        aspectRatio: "landscape",
    },
    {
        id: 24,
        src: "https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800&q=80",
        alt: "White water rafting",
        categories: ["Adventure"],
        caption: "Grade 5 rapids — white water rafting below Victoria Falls.",
        location: "Zambezi River",
        featured: false,
        aspectRatio: "landscape",
    },

    // ── Accommodations ────────────────────────────────────
    {
        id: 25,
        src: "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=800&q=80",
        alt: "Luxury safari tent interior",
        categories: ["Accommodations"],
        caption: "Where luxury meets the wild — our premium tented suites.",
        location: "Hwange National Park",
        featured: false,
        aspectRatio: "landscape",
    },
    {
        id: 26,
        src: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80",
        alt: "Safari lodge bedroom with view",
        categories: ["Accommodations"],
        caption: "Wake up to panoramic views of the African bush.",
        location: "Mana Pools",
        featured: false,
        aspectRatio: "landscape",
    },
    {
        id: 27,
        src: "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&q=80",
        alt: "Outdoor dining under the stars",
        categories: ["Accommodations"],
        caption: "Fine dining under a canopy of stars in the African bush.",
        location: "Hwange National Park",
        featured: false,
        aspectRatio: "landscape",
    },
    {
        id: 28,
        src: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80",
        alt: "Infinity pool overlooking savanna",
        categories: ["Accommodations"],
        caption: "Relax by the infinity pool with sweeping views of the plains.",
        location: "Victoria Falls",
        featured: false,
        aspectRatio: "landscape",
    },
    {
        id: 29,
        src: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80",
        alt: "Treehouse lodge at night",
        categories: ["Accommodations"],
        caption: "Our signature treehouse lodges — sleeping among the treetops.",
        location: "Hwange National Park",
        featured: false,
        aspectRatio: "portrait",
    },

    // ── Extra featured / mixed ────────────────────────────
    {
        id: 30,
        src: "https://images.unsplash.com/photo-1517512006864-7edc3b933137?w=800&q=80",
        alt: "Flamingos on a lake",
        categories: ["Wildlife", "Landscapes"],
        caption: "A sea of pink — thousands of flamingos on a soda lake.",
        location: "Lake Chivero",
        featured: false,
        aspectRatio: "landscape",
    },
    {
        id: 31,
        src: "https://images.unsplash.com/photo-1549480017-d76466a4b7e8?w=800&q=80",
        alt: "Cheetah scanning the horizon",
        categories: ["Wildlife"],
        caption: "The fastest land animal pauses to scan for prey.",
        location: "Hwange National Park",
        featured: false,
        aspectRatio: "landscape",
    },
    {
        id: 32,
        src: "https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800&q=80",
        alt: "Golden hour game drive",
        categories: ["Adventure", "Landscapes"],
        caption: "Golden hour paints the bush in warm tones as the game drive continues.",
        location: "Hwange National Park",
        featured: false,
        aspectRatio: "landscape",
    },
];
