export type GalleryCategory =
    | "Wildlife"
    | "Landscapes"
    | "Cultural"
    | "Adventure"
    | "Accommodations";

export interface GalleryImage {
    id: number;
    src: string;
    alt: string;
    categories: GalleryCategory[];
    caption: string;
    location?: string;
    featured: boolean;
    /** "landscape" | "portrait" | "square" — drives masonry row-span */
    aspectRatio: "landscape" | "portrait" | "square";
}

export const galleryCategories: GalleryCategory[] = [
    "Wildlife",
    "Landscapes",
    "Cultural",
    "Adventure",
    "Accommodations",
];

/**
 * 32 curated safari images organised by category.
 * All paths reference files in /public/images/safari/.
 */
export const galleryImages: GalleryImage[] = [
    // ── Wildlife ──────────────────────────────────────────
    {
        id: 1,
        src: "/images/safari/lioness-rain.jpg",
        alt: "Male lion resting in golden grassland",
        categories: ["Wildlife"],
        caption: "King of the savanna — a male lion surveys his territory at dawn.",
        location: "Hwange National Park",
        featured: true,
        aspectRatio: "landscape",
    },
    {
        id: 2,
        src: "/images/safari/elephants-waterhole.jpg",
        alt: "Elephant herd at a watering hole",
        categories: ["Wildlife"],
        caption: "An elephant family gathers at the river during the dry season.",
        location: "Mana Pools",
        featured: true,
        aspectRatio: "portrait",
    },
    {
        id: 3,
        src: "/images/safari/leopard-tree.jpg",
        alt: "Leopard on a tree branch",
        categories: ["Wildlife"],
        caption: "A leopard watches from its vantage point high in a marula tree.",
        location: "Hwange National Park",
        featured: false,
        aspectRatio: "portrait",
    },
    {
        id: 4,
        src: "/images/safari/oryx-dunes.jpg",
        alt: "Giraffe silhouette at sunset",
        categories: ["Wildlife", "Landscapes"],
        caption: "Giraffes framed against a fiery African sunset.",
        location: "Zambezi Valley",
        featured: true,
        aspectRatio: "landscape",
    },
    {
        id: 5,
        src: "/images/safari/wild-dogs.jpg",
        alt: "African wild dogs hunting",
        categories: ["Wildlife"],
        caption: "Painted wolves — Africa's most efficient predators on the move.",
        location: "Mana Pools",
        featured: true,
        aspectRatio: "landscape",
    },
    {
        id: 6,
        src: "/images/safari/buffalo-grazing.jpg",
        alt: "Zebras at waterhole",
        categories: ["Wildlife"],
        caption: "A dazzle of zebras reflected in still waters.",
        location: "Hwange National Park",
        featured: false,
        aspectRatio: "square",
    },
    {
        id: 7,
        src: "/images/safari/rhino.jpg",
        alt: "Rhino mother and calf",
        categories: ["Wildlife"],
        caption: "A rare sighting — a white rhino mother and calf in the early morning mist.",
        location: "Matobo Hills",
        featured: false,
        aspectRatio: "landscape",
    },
    {
        id: 8,
        src: "/images/safari/hippos-grass.jpg",
        alt: "Hippos in the Zambezi River",
        categories: ["Wildlife"],
        caption: "Hippos cool off in the powerful currents of the Zambezi.",
        location: "Zambezi River",
        featured: false,
        aspectRatio: "landscape",
    },

    // ── Landscapes ────────────────────────────────────────
    {
        id: 9,
        src: "/images/safari/dead-tree-desert.jpg",
        alt: "African savanna at golden hour",
        categories: ["Landscapes"],
        caption: "Endless golden plains stretch beneath a dramatic African sky.",
        location: "Hwange National Park",
        featured: true,
        aspectRatio: "landscape",
    },
    {
        id: 10,
        src: "/images/safari/victoria-falls-wide.jpg",
        alt: "Victoria Falls panoramic view",
        categories: ["Landscapes", "Adventure"],
        caption: "The Smoke that Thunders — Victoria Falls in full flood.",
        location: "Victoria Falls",
        featured: true,
        aspectRatio: "portrait",
    },
    {
        id: 11,
        src: "/images/safari/dunes-moody.jpg",
        alt: "Sunrise over misty valley",
        categories: ["Landscapes"],
        caption: "Dawn breaks over the misty valleys of the Eastern Highlands.",
        location: "Eastern Highlands",
        featured: false,
        aspectRatio: "landscape",
    },
    {
        id: 12,
        src: "/images/safari/welwitschia.jpg",
        alt: "Acacia tree silhouette",
        categories: ["Landscapes"],
        caption: "The iconic silhouette of an acacia tree against a painted sky.",
        location: "Hwange National Park",
        featured: false,
        aspectRatio: "square",
    },
    {
        id: 13,
        src: "/images/safari/dunes-panorama.jpg",
        alt: "Starry night over savanna",
        categories: ["Landscapes"],
        caption: "The Milky Way arches over the African bush — zero light pollution.",
        location: "Hwange National Park",
        featured: false,
        aspectRatio: "landscape",
    },
    {
        id: 14,
        src: "/images/safari/elephant-charging.jpg",
        alt: "Baobab tree at sunset",
        categories: ["Landscapes"],
        caption: "Ancient baobabs stand sentinel over the changing seasons.",
        location: "Gonarezhou National Park",
        featured: false,
        aspectRatio: "portrait",
    },

    // ── Cultural ──────────────────────────────────────────
    {
        id: 15,
        src: "/images/safari/kudu.jpg",
        alt: "Traditional village scene",
        categories: ["Cultural"],
        caption: "Sharing stories and traditions with the local community.",
        location: "Masvingo Province",
        featured: true,
        aspectRatio: "landscape",
    },
    {
        id: 16,
        src: "/images/safari/leopard-walking.jpg",
        alt: "Traditional dancers performing",
        categories: ["Cultural"],
        caption: "Vibrant traditional dances celebrate centuries-old heritage.",
        location: "Victoria Falls Village",
        featured: false,
        aspectRatio: "square",
    },
    {
        id: 17,
        src: "/images/safari/raptor-ground.jpg",
        alt: "Local artisan crafting",
        categories: ["Cultural"],
        caption: "Skilled artisans create beautiful sculptures from local stone.",
        location: "Tengenenge",
        featured: false,
        aspectRatio: "portrait",
    },
    {
        id: 18,
        src: "/images/safari/martial-eagle.jpg",
        alt: "Traditional basket weaving",
        categories: ["Cultural"],
        caption: "The intricate art of basket weaving passed down through generations.",
        location: "Binga",
        featured: false,
        aspectRatio: "landscape",
    },

    // ── Adventure ─────────────────────────────────────────
    {
        id: 19,
        src: "/images/safari/elephant-river.jpg",
        alt: "Safari vehicle at sunrise",
        categories: ["Adventure"],
        caption: "The adventure begins — setting out on an early morning game drive.",
        location: "Hwange National Park",
        featured: true,
        aspectRatio: "landscape",
    },
    {
        id: 20,
        src: "/images/safari/river-aerial.jpg",
        alt: "Canoe safari on the Zambezi",
        categories: ["Adventure"],
        caption: "Paddling silently past hippos and crocs on a canoe safari.",
        location: "Mana Pools",
        featured: false,
        aspectRatio: "landscape",
    },
    {
        id: 21,
        src: "/images/safari/elephant-tusker.jpg",
        alt: "Walking safari guide with guests",
        categories: ["Adventure"],
        caption: "Up close and personal — a guided walking safari through the bush.",
        location: "Mana Pools",
        featured: false,
        aspectRatio: "portrait",
    },
    {
        id: 22,
        src: "/images/safari/victoria-falls-aerial.jpg",
        alt: "Bungee jumping at Victoria Falls Bridge",
        categories: ["Adventure"],
        caption: "The ultimate thrill — 111m bungee jump over the Zambezi gorge.",
        location: "Victoria Falls Bridge",
        featured: false,
        aspectRatio: "portrait",
    },
    {
        id: 23,
        src: "/images/safari/victoria-falls-close.jpg",
        alt: "Hot air balloon over savanna",
        categories: ["Adventure", "Landscapes"],
        caption: "A breathtaking bird's-eye view from a hot air balloon at sunrise.",
        location: "Hwange National Park",
        featured: false,
        aspectRatio: "landscape",
    },
    {
        id: 24,
        src: "/images/safari/elephants-swimming.jpg",
        alt: "White water rafting",
        categories: ["Adventure"],
        caption: "Grade 5 rapids — white water rafting below Victoria Falls.",
        location: "Zambezi River",
        featured: false,
        aspectRatio: "landscape",
    },

    // ── Accommodations ────────────────────────────────────
    {
        id: 25,
        src: "/images/safari/sable-antelope.jpg",
        alt: "Luxury safari tent interior",
        categories: ["Accommodations"],
        caption: "Where luxury meets the wild — our premium tented suites.",
        location: "Hwange National Park",
        featured: false,
        aspectRatio: "landscape",
    },
    {
        id: 26,
        src: "/images/safari/elephants-fighting.jpg",
        alt: "Safari lodge bedroom with view",
        categories: ["Accommodations"],
        caption: "Wake up to panoramic views of the African bush.",
        location: "Mana Pools",
        featured: false,
        aspectRatio: "landscape",
    },
    {
        id: 27,
        src: "/images/safari/elephants-herd-waterhole.jpg",
        alt: "Outdoor dining under the stars",
        categories: ["Accommodations"],
        caption: "Fine dining under a canopy of stars in the African bush.",
        location: "Hwange National Park",
        featured: false,
        aspectRatio: "landscape",
    },
    {
        id: 28,
        src: "/images/safari/wildebeest.jpg",
        alt: "Infinity pool overlooking savanna",
        categories: ["Accommodations"],
        caption: "Relax by the infinity pool with sweeping views of the plains.",
        location: "Victoria Falls",
        featured: false,
        aspectRatio: "landscape",
    },
    {
        id: 29,
        src: "/images/safari/elephant-front.jpg",
        alt: "Treehouse lodge at night",
        categories: ["Accommodations"],
        caption: "Our signature treehouse lodges — sleeping among the treetops.",
        location: "Hwange National Park",
        featured: false,
        aspectRatio: "portrait",
    },

    // ── Extra featured / mixed ────────────────────────────
    {
        id: 30,
        src: "/images/safari/hippos-mud.jpg",
        alt: "Flamingos on a lake",
        categories: ["Wildlife", "Landscapes"],
        caption: "A sea of pink — thousands of flamingos on a soda lake.",
        location: "Lake Chivero",
        featured: false,
        aspectRatio: "landscape",
    },
    {
        id: 31,
        src: "/images/safari/lioness-rain.jpg",
        alt: "Cheetah scanning the horizon",
        categories: ["Wildlife"],
        caption: "The fastest land animal pauses to scan for prey.",
        location: "Hwange National Park",
        featured: false,
        aspectRatio: "landscape",
    },
    {
        id: 32,
        src: "/images/safari/elephants-waterhole.jpg",
        alt: "Golden hour game drive",
        categories: ["Adventure", "Landscapes"],
        caption: "Golden hour paints the bush in warm tones as the game drive continues.",
        location: "Hwange National Park",
        featured: false,
        aspectRatio: "landscape",
    },
];
