import { Hotel } from './types/hotel';

export const hotels: Hotel[] = [
    {
        id: 'h1',
        slug: 'the-elephant-camp-victoria-falls',
        name: 'The Elephant Camp',
        propertyType: 'lodge',
        starRating: 5,
        location: {
            destination: 'Victoria Falls',
            address: 'Victoria Falls National Park, Zimbabwe',
            coordinates: { lat: -17.95, lng: 25.85 },
            distanceToVictoriaFalls: 10,
            distanceToAirport: 20,
        },
        shortDescription: 'An exclusive, luxury lodge under canvas, with breathtaking views of the Victoria Falls spray.',
        longDescription: 'The Elephant Camp is situated on a private concession within the Victoria Falls National Park, offering guests an intimate safari experience. Each luxury suite features a private plunge pool and an outdoor shower. The camp is home to the wild horizons elephant sanctuary, where guests can interact with these majestic creatures.',
        highlights: [
            'Private plunge pool in every suite',
            'Elephant interactions on-site',
            'Views of the Victoria Falls spray',
            'All-inclusive fine dining',
        ],
        images: {
            thumbnail: '/images/safari/dunes-moody.jpg',
            gallery: [
                '/images/safari/lioness-rain.jpg',
                '/images/safari/elephant-tusker.jpg',
                '/images/safari/elephant-front.jpg',
            ],
        },
        pricing: {
            currency: 'USD',
            pricePerNightFrom: 850,
            includedInRate: ['All meals', 'Local drinks', 'Game drives', 'Victoria Falls tour'],
        },
        roomTypes: [
            {
                id: 'r1',
                name: 'Luxury Tented Suite',
                description: 'Spacious tented suite with private deck and plunge pool.',
                maxOccupancy: 2,
                bedConfiguration: '1 King or 2 Twins',
                amenities: ['Air conditioning', 'Minibar', 'Safe', 'Outdoor shower'],
                images: ['/images/safari/dunes-moody.jpg'],
                price: 850,
                available: true,
            }
        ],
        amenities: {
            general: ['Free WiFi', 'Swimming Pool', 'Lounge', 'Dining Area'],
            room: ['Air Conditioning', 'Safe', 'Hairdryer'],
            dining: ['Gourmet Restaurant', 'Bar', 'Private Dining'],
            activities: ['Game Drives', 'Elephant Interaction', 'Spa'],
            services: ['Airport Shuttle', 'Laundry', 'Concierge'],
        },
        mealPlans: ['Fully Inclusive'],
        policies: {
            checkIn: '14:00',
            checkOut: '10:00',
            cancellation: 'Free cancellation up to 30 days before arrival.',
            children: 'Children over 7 years are welcome.',
            pets: 'No pets allowed.',
        },
        reviews: {
            averageRating: 4.9,
            totalReviews: 124,
            ratingBreakdown: {
                cleanliness: 5.0,
                service: 4.9,
                location: 4.8,
                value: 4.7,
                facilities: 4.9,
            },
            recentReviews: [],
        },
        features: {
            featured: true,
            popular: true,
            familyFriendly: true,
        },
        tags: ['Luxury', 'Safari', 'Victoria Falls'],
    },
    {
        id: 'h2',
        slug: 'victoria-falls-safari-lodge',
        name: 'Victoria Falls Safari Lodge',
        propertyType: 'hotel',
        starRating: 4,
        location: {
            destination: 'Victoria Falls',
            address: 'Stand 471B, Squire Cummings Rd, Victoria Falls',
            coordinates: { lat: -17.92, lng: 25.82 },
            distanceToVictoriaFalls: 4,
            distanceToAirport: 21,
        },
        shortDescription: 'Built on a high plateau, this lodge offers unparalleled views of the African bushveld and a busy waterhole.',
        longDescription: 'Victoria Falls Safari Lodge is built on a plateau bordering the Zambezi National Park, offering breathtaking views of the African bush and a wildlife-rich waterhole. The lodge is located just 4km from the Victoria Falls, and a complimentary shuttle service is available.',
        highlights: [
            'Overlooks a busy wildlife waterhole',
            'The Boma - Dinner & Drum Show',
            'Stunning sunset views from Buffalo Bar',
            'Complimentary shuttle to town',
        ],
        images: {
            thumbnail: '/images/safari/wild-dogs.jpg',
            gallery: [
                '/images/safari/elephants-swimming.jpg',
                '/images/safari/leopard-tree.jpg',
            ],
        },
        pricing: {
            currency: 'USD',
            pricePerNightFrom: 280,
            includedInRate: ['Breakfast'],
        },
        roomTypes: [
            {
                id: 'r2',
                name: 'Standard Room',
                description: 'Comfortable room with private balcony overlooking the bush.',
                maxOccupancy: 2,
                bedConfiguration: '2 Twins',
                amenities: ['Air conditioning', 'Safe', 'Coffee maker'],
                images: ['/images/safari/oryx-dunes.jpg'],
                price: 280,
                available: true,
            }
        ],
        amenities: {
            general: ['Free WiFi', 'Pool', 'Fitness Center'],
            room: ['Air Conditioning', 'En-suite Bathroom'],
            dining: ['MaKuwa-Kuwa Restaurant', 'Buffalo Bar', 'The Boma'],
            activities: ['Vulture Culture experience', 'Bird watching'],
            services: ['Shuttle Bus', 'Curio Shop'],
        },
        mealPlans: ['Bed & Breakfast', 'Half Board', 'Full Board'],
        policies: {
            checkIn: '14:00',
            checkOut: '10:00',
            cancellation: 'Free cancellation up to 14 days before arrival.',
            children: 'All ages welcome.',
            pets: 'No pets allowed.',
        },
        reviews: {
            averageRating: 4.5,
            totalReviews: 850,
            ratingBreakdown: {
                cleanliness: 4.6,
                service: 4.5,
                location: 4.7,
                value: 4.4,
                facilities: 4.5,
            },
            recentReviews: [],
        },
        features: {
            popular: true,
            familyFriendly: true,
        },
        tags: ['Views', 'Waterhole', 'Boma'],
    },
    {
        id: 'h3',
        slug: 'shoestrings-backpackers-vic-falls',
        name: 'Shoestrings Backpackers',
        propertyType: 'guesthouse',
        starRating: 2,
        location: {
            destination: 'Victoria Falls',
            address: '12 Parkway Dr, Victoria Falls',
            coordinates: { lat: -17.928, lng: 25.841 },
            distanceToVictoriaFalls: 1.5,
            distanceToAirport: 20,
        },
        shortDescription: 'The heart of Victoria Falls social life, perfect for budget-conscious travelers and backpackers.',
        longDescription: 'Shoestrings is a legendary backpackers lodge in Victoria Falls, known for its friendly atmosphere, vibrant bar, and central location. It offers a variety of accommodation from camping to private rooms.',
        highlights: [
            'Vibrant social atmosphere',
            'Central location - walk to town',
            'Budget-friendly options',
            'Frequent live music and events',
        ],
        images: {
            thumbnail: '/images/safari/elephants-swimming.jpg',
            gallery: [
                '/images/safari/leopard-tree.jpg',
            ],
        },
        pricing: {
            currency: 'USD',
            pricePerNightFrom: 45,
            includedInRate: ['Room Only'],
        },
        roomTypes: [
            {
                id: 'r3',
                name: 'Private Room',
                description: 'Simple private room with shared or en-suite bathroom.',
                maxOccupancy: 2,
                bedConfiguration: '1 Double or 2 Twins',
                amenities: ['Fan', 'Mosquito net'],
                images: ['/images/safari/dunes-moody.jpg'],
                price: 45,
                available: true,
            }
        ],
        amenities: {
            general: ['WiFi in public areas', 'Bar', 'Communal Kitchen'],
            room: ['Fan', 'Mosquito Net'],
            dining: ['Cafe', 'Bar with wood-fired pizza'],
            activities: ['Social events', 'Booking center'],
            services: ['Linen included'],
        },
        mealPlans: ['Room Only'],
        policies: {
            checkIn: '13:00',
            checkOut: '10:00',
            cancellation: 'Free cancellation up to 48 hours before arrival.',
            children: 'Children welcome.',
            pets: 'Enquire with management.',
        },
        reviews: {
            averageRating: 4.0,
            totalReviews: 320,
            ratingBreakdown: {
                cleanliness: 3.8,
                service: 4.2,
                location: 4.8,
                value: 4.6,
                facilities: 3.5,
            },
            recentReviews: [],
        },
        features: {
            popular: true,
        },
        tags: ['Budget', 'Backpackers', 'Central'],
    },
    {
        id: 'h4',
        slug: 'linkwasha-camp-hwange',
        name: 'Linkwasha Camp',
        propertyType: 'camp',
        starRating: 5,
        location: {
            destination: 'Hwange National Park',
            address: 'Linkwasha Concession, Hwange National Park',
            coordinates: { lat: -19.12, lng: 27.21 },
            distanceToVictoriaFalls: 180,
            distanceToAirport: 190,
        },
        shortDescription: 'A luxurious camp in the private Linkwasha Concession, overlooking a teeming waterhole.',
        longDescription: 'Linkwasha Camp is situated in the multi-award-winning private Linkwasha Concession in Hwange National Park. The camp is highly contemporary and offers magnificent views over the plains and waterhole.',
        highlights: [
            'Premier safari destination in Hwange',
            'Exclusive private concession',
            'Abundant wildlife sightings',
            'Contemporary luxury design',
        ],
        images: {
            thumbnail: '/images/safari/elephants-swimming.jpg',
            gallery: [
                '/images/safari/elephants-fighting.jpg',
            ],
        },
        pricing: {
            currency: 'USD',
            pricePerNightFrom: 720,
            includedInRate: ['All meals', 'Local drinks', 'Park fees', 'Game drives'],
        },
        roomTypes: [
            {
                id: 'r4',
                name: 'Luxury Tent',
                description: 'Large luxury tent with private viewing deck.',
                maxOccupancy: 2,
                bedConfiguration: '1 King or 2 Twins',
                amenities: ['Air conditioning', 'En-suite shower', 'Safe'],
                images: ['/images/safari/leopard-tree.jpg'],
                price: 720,
                available: true,
            }
        ],
        amenities: {
            general: ['Pool', 'Lounge', 'Fire pit'],
            room: ['Air Conditioning', 'Safe'],
            dining: ['Dining tent', 'Outdoor boma'],
            activities: ['Morning & Night Game Drives', 'Walking Safaris'],
            services: ['Laundry', 'Transfers'],
        },
        mealPlans: ['Fully Inclusive'],
        policies: {
            checkIn: '14:00',
            checkOut: '11:00',
            cancellation: 'Strict cancellation policy applies.',
            children: 'Children 6+ years welcome.',
            pets: 'No pets.',
        },
        reviews: {
            averageRating: 5.0,
            totalReviews: 45,
            ratingBreakdown: {
                cleanliness: 5.0,
                service: 5.0,
                location: 5.0,
                value: 4.8,
                facilities: 5.0,
            },
            recentReviews: [],
        },
        features: {
            featured: true,
            ecoFriendly: true,
        },
        tags: ['Luxury', 'Safari', 'Wilderness'],
    },
    {
        id: 'h5',
        slug: 'ruckomechi-camp-mana-pools',
        name: 'Ruckomechi Camp',
        propertyType: 'camp',
        starRating: 5,
        location: {
            destination: 'Mana Pools',
            address: 'Mana Pools National Park, Zimbabwe',
            coordinates: { lat: -15.75, lng: 29.35 },
            distanceToVictoriaFalls: 450,
            distanceToAirport: 20,
        },
        shortDescription: 'Nestled amongst grove of mahogany and acacia trees, with views of the Zambezi River.',
        longDescription: 'Ruckomechi Camp is situated in a large private concession in Mana Pools National Park. The camp overlooks the Zambezi River with the mountains of the Rift Valley escarpment as a backdrop.',
        highlights: [
            'Overlooks the Zambezi River',
            'Private concession exclusivity',
            'Famous for "out of Africa" star beds',
            'Excellent elephant and lion viewing',
        ],
        images: {
            thumbnail: '/images/safari/wildebeest.jpg',
            gallery: [
                '/images/safari/lioness-rain.jpg',
            ],
        },
        pricing: {
            currency: 'USD',
            pricePerNightFrom: 680,
            includedInRate: ['All meals', 'Drinks', 'Safari activities'],
        },
        roomTypes: [
            {
                id: 'r5',
                name: 'Luxury Suite',
                description: 'En-suite tents with private viewing decks along the river.',
                maxOccupancy: 2,
                bedConfiguration: '1 King',
                amenities: ['Fan', 'Safe', 'Outdoor bath'],
                images: ['/images/safari/wild-dogs.jpg'],
                price: 680,
                available: true,
            }
        ],
        amenities: {
            general: ['Dining room', 'Pub', 'Plunge pool'],
            room: ['Outdoor bath', 'Private Deck'],
            dining: ['Riverbank dining', 'Picnic lunches'],
            activities: ['Game drives', 'Walking safaris', 'Canoeing'],
            services: ['Laundry', 'Valet'],
        },
        mealPlans: ['Fully Inclusive'],
        policies: {
            checkIn: '12:00',
            checkOut: '10:00',
            cancellation: 'Strict cancellation applies.',
            children: 'Children 6+ welcome.',
            pets: 'No pets.',
        },
        reviews: {
            averageRating: 4.8,
            totalReviews: 32,
            ratingBreakdown: {
                cleanliness: 4.9,
                service: 4.8,
                location: 5.0,
                value: 4.6,
                facilities: 4.7,
            },
            recentReviews: [],
        },
        features: {
            featured: true,
        },
        tags: ['Zambezi', 'River', 'Remote'],
    },
    {
        id: 'h6',
        slug: 'changa-safari-camp-lake-kariba',
        name: 'Changa Safari Camp',
        propertyType: 'camp',
        starRating: 4,
        location: {
            destination: 'Lake Kariba',
            address: 'Matusadona National Park, Lake Kariba',
            coordinates: { lat: -16.85, lng: 28.52 },
            distanceToVictoriaFalls: 400,
            distanceToAirport: 350,
        },
        shortDescription: 'A hideaway in Matusadona National Park, on the shores of Lake Kariba.',
        longDescription: 'Changa Safari Camp is a luxury tented camp situated on the shores of Lake Kariba, within the Matusadona National Park. It combines a true safari experience with the beauty of the lake.',
        highlights: [
            'Beach-side atmosphere on the lake',
            'Matusadona National Park access',
            'Legendary tiger fishing',
            'Incredible sunsets over the lake',
        ],
        images: {
            thumbnail: '/images/safari/river-aerial.jpg',
            gallery: [
                '/images/safari/elephants-swimming.jpg',
            ],
        },
        pricing: {
            currency: 'USD',
            pricePerNightFrom: 520,
            includedInRate: ['All meals', 'Activities'],
        },
        roomTypes: [
            {
                id: 'r6',
                name: 'Deluxe Suite',
                description: 'Tented suite with lake views and outdoor shower.',
                maxOccupancy: 2,
                bedConfiguration: '1 King',
                amenities: ['Fan', 'Safe', 'Outdoor bath'],
                images: ['/images/safari/elephant-tusker.jpg'],
                price: 520,
                available: true,
            }
        ],
        amenities: {
            general: ['Pool', 'Lounge', 'Library'],
            room: ['Outdoor bath', 'Fans'],
            dining: ['Dining deck', 'Beach dinner'],
            activities: ['Boating', 'Fishing', 'Game drives'],
            services: ['Laundry', 'Transfers'],
        },
        mealPlans: ['Fully Inclusive'],
        policies: {
            checkIn: '14:00',
            checkOut: '10:00',
            cancellation: '30 days cancellation.',
            children: 'Children 7+ welcome.',
            pets: 'None.',
        },
        reviews: {
            averageRating: 4.7,
            totalReviews: 28,
            ratingBreakdown: {
                cleanliness: 4.7,
                service: 4.9,
                location: 4.9,
                value: 4.5,
                facilities: 4.6,
            },
            recentReviews: [],
        },
        features: {
            ecoFriendly: true,
        },
        tags: ['Lake', 'Fishing', 'Relaxing'],
    },
    {
        id: 'h7',
        slug: 'hwange-safari-lodge',
        name: 'Hwange Safari Lodge',
        propertyType: 'hotel',
        starRating: 3,
        location: {
            destination: 'Hwange National Park',
            address: 'Bulawayo-Victoria Falls Rd, Hwange National Park',
            coordinates: { lat: -18.73, lng: 27.02 },
            distanceToVictoriaFalls: 175,
            distanceToAirport: 185,
        },
        shortDescription: 'Ideal for anyone who wants to see the wild but does not want to give up hotel comforts.',
        longDescription: 'Hwange Safari Lodge is located just outside the Hwange National Park. It is a large hotel with over 100 rooms, making it a great base for larger groups or those seeking familiar hotel amenities.',
        highlights: [
            'Next to Hwange National Park gate',
            'Large swimming pool',
            'Wild animals frequently visit the grounds',
            'Full conference facilities',
        ],
        images: {
            thumbnail: '/images/safari/lioness-rain.jpg',
            gallery: [
                '/images/safari/wild-dogs.jpg',
            ],
        },
        pricing: {
            currency: 'USD',
            pricePerNightFrom: 220,
            includedInRate: ['Breakfast'],
        },
        roomTypes: [
            {
                id: 'r7',
                name: 'Standard Twin',
                description: 'Modern hotel room with national park or pool views.',
                maxOccupancy: 2,
                bedConfiguration: '2 Twins',
                amenities: ['Air conditioning', 'TV', 'Coffee maker'],
                images: ['/images/safari/elephant-front.jpg'],
                price: 220,
                available: true,
            }
        ],
        amenities: {
            general: ['Large Pool', 'Tennis court', 'Gift shop'],
            room: ['Air Conditioning', 'Satellite TV'],
            dining: ['Restaurant', 'Poolside bar'],
            activities: ['Guided tours', 'Bush walks'],
            services: ['24-hour reception', 'Room service'],
        },
        mealPlans: ['Bed & Breakfast', 'Half Board'],
        policies: {
            checkIn: '14:00',
            checkOut: '11:00',
            cancellation: '7 days cancellation.',
            children: 'All ages welcome.',
            pets: 'No.',
        },
        reviews: {
            averageRating: 4.1,
            totalReviews: 240,
            ratingBreakdown: {
                cleanliness: 4.0,
                service: 4.2,
                location: 4.5,
                value: 4.1,
                facilities: 3.9,
            },
            recentReviews: [],
        },
        features: {
            familyFriendly: true,
        },
        tags: ['Convenient', 'Large', 'Family'],
    },
    {
        id: 'h8',
        slug: 'amalinda-lodge-matobo',
        name: 'Amalinda Lodge',
        propertyType: 'eco-lodge',
        starRating: 4,
        location: {
            destination: 'Matobo Hills',
            address: 'Matobo Hills National Park, near Bulawayo',
            coordinates: { lat: -20.52, lng: 28.51 },
            distanceToVictoriaFalls: 450,
            distanceToAirport: 50,
        },
        shortDescription: 'Built into the ancient granite boulders of the Matobo Hills.',
        longDescription: 'Amalinda Lodge is a premier safari lodge in the Matobo Hills. The lodgings are built within the massive granite outcrops, creating a unique and atmospheric experience.',
        highlights: [
            'UNESCO World Heritage location',
            'Unique granite boulder architecture',
            'Rhino tracking on foot',
            'Ancient San Bushmen rock art',
        ],
        images: {
            thumbnail: '/images/safari/lioness-rain.jpg',
            gallery: [
                '/images/safari/oryx-dunes.jpg',
            ],
        },
        pricing: {
            currency: 'USD',
            pricePerNightFrom: 420,
            includedInRate: ['All meals', 'Local drinks', 'Activities'],
        },
        roomTypes: [
            {
                id: 'r8',
                name: 'Rock Suite',
                description: 'Atmospheric suite built into the boulders.',
                maxOccupancy: 2,
                bedConfiguration: '1 King',
                amenities: ['Fan', 'Safe', 'Outdoor shower'],
                images: ['/images/safari/hippos-mud.jpg'],
                price: 420,
                available: true,
            }
        ],
        amenities: {
            general: ['Rock pool', 'Spa', 'Library'],
            room: ['Fan', 'Safe'],
            dining: ['Fine dining room', 'Cave bar'],
            activities: ['Rhino tracking', 'Rock art tours', 'Cultural visits'],
            services: ['Laundry', 'Transfers'],
        },
        mealPlans: ['Fully Inclusive'],
        policies: {
            checkIn: '14:00',
            checkOut: '10:00',
            cancellation: '30 days cancellation.',
            children: '12+ years preferred.',
            pets: 'No.',
        },
        reviews: {
            averageRating: 4.9,
            totalReviews: 64,
            ratingBreakdown: {
                cleanliness: 4.9,
                service: 5.0,
                location: 5.0,
                value: 4.7,
                facilities: 4.9,
            },
            recentReviews: [],
        },
        features: {
            featured: true,
            ecoFriendly: true,
        },
        tags: ['History', 'Rocks', 'Rhino'],
    },
    {
        id: 'h9',
        slug: 'bumi-hills-safari-lodge-kariba',
        name: 'Bumi Hills Safari Lodge',
        propertyType: 'lodge',
        starRating: 5,
        location: {
            destination: 'Lake Kariba',
            address: 'Bumi Hills, Lake Kariba',
            coordinates: { lat: -16.92, lng: 28.32 },
            distanceToVictoriaFalls: 380,
            distanceToAirport: 340,
        },
        shortDescription: 'Commanding views of Lake Kariba from its hilltop location.',
        longDescription: 'Bumi Hills Safari Lodge is set on a range of remote hills overlooking Lake Kariba. With a signature infinity pool and spa, it offers luxury in one of Zimbabwes most beautiful settings.',
        highlights: [
            'Panoramic Lake Kariba views',
            'Luxury infinity pool',
            'Private safari concession',
            'World-class angling (tiger fish)',
        ],
        images: {
            thumbnail: '/images/safari/hippos-mud.jpg',
            gallery: [
                '/images/safari/elephant-tusker.jpg',
            ],
        },
        pricing: {
            currency: 'USD',
            pricePerNightFrom: 560,
            includedInRate: ['All meals', 'Drinks', 'Safari activities'],
        },
        roomTypes: [
            {
                id: 'r9',
                name: 'Lake View Suite',
                description: 'Luxury suite with private balcony overlooking the lake.',
                maxOccupancy: 2,
                bedConfiguration: '1 King',
                amenities: ['Air conditioning', 'Minibar', 'Safe'],
                images: ['/images/safari/river-aerial.jpg'],
                price: 560,
                available: true,
            }
        ],
        amenities: {
            general: ['Infinity Pool', 'Spa', 'Gym'],
            room: ['Air Conditioning', 'Balcony'],
            dining: ['Gourmet Restaurant', 'Terrace Bar'],
            activities: ['Boat safaris', 'Tiger fishing', 'Game drives'],
            services: ['Lodge transfers', 'Laundry'],
        },
        mealPlans: ['Fully Inclusive'],
        policies: {
            checkIn: '14:00',
            checkOut: '11:00',
            cancellation: 'Strict cancellation.',
            children: 'Children welcome.',
            pets: 'No.',
        },
        reviews: {
            averageRating: 4.9,
            totalReviews: 42,
            ratingBreakdown: {
                cleanliness: 4.9,
                service: 4.9,
                location: 5.0,
                value: 4.7,
                facilities: 5.0,
            },
            recentReviews: [],
        },
        features: {
            featured: true,
        },
        tags: ['Views', 'Lake', 'Luxury'],
    },
    {
        id: 'h10',
        slug: 'little-makalolo-hwange',
        name: 'Little Makalolo',
        propertyType: 'camp',
        starRating: 4,
        location: {
            destination: 'Hwange National Park',
            address: 'Linkwasha Concession, Hwange National Park',
            coordinates: { lat: -19.15, lng: 27.25 },
            distanceToVictoriaFalls: 185,
            distanceToAirport: 195,
        },
        shortDescription: 'An authentic bush camp in the heart of Hwange National Park.',
        longDescription: 'Little Makalolo is one of Hwange National Parks pioneers, providing an authentic bush experience. The camp is small and intimate, overlooking a busy waterhole.',
        highlights: [
            'Busy waterhole in front of camp',
            'Intimate bush atmosphere',
            'Excellent game viewing from the log pile hide',
            'Part of a massive private concession',
        ],
        images: {
            thumbnail: '/images/safari/elephants-waterhole.jpg',
            gallery: [
                '/images/safari/leopard-tree.jpg',
            ],
        },
        pricing: {
            currency: 'USD',
            pricePerNightFrom: 580,
            includedInRate: ['All meals', 'Drinks', 'Safari activities'],
        },
        roomTypes: [
            {
                id: 'r10',
                name: 'Safari Tent',
                description: 'Classic safari tent with en-suite facilities.',
                maxOccupancy: 2,
                bedConfiguration: '2 Twins',
                amenities: ['Fan', 'Safe', 'Outdoor shower'],
                images: ['/images/safari/elephants-fighting.jpg'],
                price: 580,
                available: true,
            }
        ],
        amenities: {
            general: ['Pool', 'Dining area', 'Fire pit'],
            room: ['Outdoor shower', 'Safe'],
            dining: ['Buffet dining', 'Bush dinners'],
            activities: ['Game drives', 'Walking safaris', 'Waterhole hide'],
            services: ['Laundry', 'Transfers'],
        },
        mealPlans: ['Fully Inclusive'],
        policies: {
            checkIn: '14:00',
            checkOut: '10:00',
            cancellation: '30 days cancellation.',
            children: 'Children 6+ welcome.',
            pets: 'No.',
        },
        reviews: {
            averageRating: 4.8,
            totalReviews: 38,
            ratingBreakdown: {
                cleanliness: 4.8,
                service: 4.9,
                location: 5.0,
                value: 4.7,
                facilities: 4.6,
            },
            recentReviews: [],
        },
        features: {
            ecoFriendly: true,
        },
        tags: ['Authentic', 'Bush', 'Waterhole'],
    },
    {
        id: 'h11',
        slug: 'zambezi-river-lodge',
        name: "A'Zambezi River Lodge",
        propertyType: 'hotel',
        starRating: 4,
        location: {
            destination: 'Victoria Falls',
            address: 'Parkway Drive, Victoria Falls',
            coordinates: { lat: -17.91, lng: 25.80 },
            distanceToVictoriaFalls: 5,
            distanceToAirport: 22,
        },
        shortDescription: 'The only hotel in Victoria Falls located right on the banks of the Zambezi River.',
        longDescription: "A'Zambezi River Lodge is located on the banks of the Zambezi River, just 5km from the Victoria Falls. The hotel offers a peaceful setting away from the town center.",
        highlights: [
            'Direct Zambezi River frontage',
            'Large tropical gardens',
            'Award-winning Amulonga Restaurant',
            'Frequent wildlife sightings on the lawns',
        ],
        images: {
            thumbnail: '/images/safari/dunes-moody.jpg',
            gallery: [
                '/images/safari/leopard-tree.jpg',
            ],
        },
        pricing: {
            currency: 'USD',
            pricePerNightFrom: 195,
            includedInRate: ['Breakfast'],
        },
        roomTypes: [
            {
                id: 'r11',
                name: 'River View Room',
                description: 'Room with balcony overlooking the Zambezi River.',
                maxOccupancy: 2,
                bedConfiguration: '1 King or 2 Twins',
                amenities: ['Air conditioning', 'Satellite TV', 'Minibar'],
                images: ['/images/safari/dunes-moody.jpg'],
                price: 195,
                available: true,
            }
        ],
        amenities: {
            general: ['Pool', 'Business center', 'Currency exchange'],
            room: ['Air Conditioning', 'TV'],
            dining: ['Amulonga Restaurant', 'Zambezi Cocktail Bar'],
            activities: ['River cruises', 'Fishing'],
            services: ['Shuttle bus', '24-hour security'],
        },
        mealPlans: ['Bed & Breakfast', 'Half Board'],
        policies: {
            checkIn: '14:00',
            checkOut: '10:00',
            cancellation: '48 hours cancellation.',
            children: 'All ages welcome.',
            pets: 'No.',
        },
        reviews: {
            averageRating: 4.4,
            totalReviews: 520,
            ratingBreakdown: {
                cleanliness: 4.5,
                service: 4.3,
                location: 4.7,
                value: 4.4,
                facilities: 4.4,
            },
            recentReviews: [],
        },
        features: {
            familyFriendly: true,
        },
        tags: ['Riverbank', 'Peaceful', 'Gardens'],
    },
    {
        id: 'h12',
        slug: 'victoria-falls-rest-camp',
        name: 'Victoria Falls Rest Camp',
        propertyType: 'guesthouse',
        starRating: 2,
        location: {
            destination: 'Victoria Falls',
            address: 'Parkway Dr, Victoria Falls',
            coordinates: { lat: -17.926, lng: 25.840 },
            distanceToVictoriaFalls: 1.2,
            distanceToAirport: 19,
        },
        shortDescription: 'The best-located budget accommodation in Victoria Falls town.',
        longDescription: 'Victoria Falls Rest Camp is ideally situated in the heart of Victoria Falls town, within walking distance of the Falls, shops, and restaurants.',
        highlights: [
            'Located in the heart of town',
            'Walking distance to the Falls',
            'A range of accommodation for all budgets',
            'Large swimming pool and restaurant',
        ],
        images: {
            thumbnail: '/images/safari/elephant-front.jpg',
            gallery: [
                '/images/safari/wildebeest.jpg',
            ],
        },
        pricing: {
            currency: 'USD',
            pricePerNightFrom: 85,
            includedInRate: ['Room Only'],
        },
        roomTypes: [
            {
                id: 'r12',
                name: 'Standard Chalet',
                description: 'Basic self-catering chalet with en-suite facilities.',
                maxOccupancy: 3,
                bedConfiguration: '3 Singles',
                amenities: ['Fan', 'Kitchenette'],
                images: ['/images/safari/dunes-panorama.jpg'],
                price: 85,
                available: true,
            }
        ],
        amenities: {
            general: ['Pool', 'Playground', 'Laundry facilities'],
            room: ['Fan', 'Fridge'],
            dining: ['In-v-els Restaurant', 'Bar'],
            activities: ['Activity booking desk'],
            services: ['24-hour security'],
        },
        mealPlans: ['Room Only'],
        policies: {
            checkIn: '14:00',
            checkOut: '10:00',
            cancellation: '7 days cancellation.',
            children: 'All ages welcome.',
            pets: 'No.',
        },
        reviews: {
            averageRating: 3.9,
            totalReviews: 180,
            ratingBreakdown: {
                cleanliness: 3.7,
                service: 4.0,
                location: 5.0,
                value: 4.5,
                facilities: 3.5,
            },
            recentReviews: [],
        },
        features: {
            familyFriendly: true,
        },
        tags: ['Budget', 'Town Center', 'Camping'],
    },
    {
        id: 'h13',
        slug: 'victoria-falls-hotel',
        name: 'The Victoria Falls Hotel',
        propertyType: 'hotel',
        starRating: 5,
        location: {
            destination: 'Victoria Falls',
            address: '1 Mallet Dr, Victoria Falls',
            coordinates: { lat: -17.925, lng: 25.842 },
            distanceToVictoriaFalls: 0.5,
            distanceToAirport: 20,
        },
        shortDescription: 'The "Grand Old Lady" of Victoria Falls, offering Edwardian grace and world-class service.',
        longDescription: 'The Victoria Falls Hotel, popularly known as the "grand old lady of the Falls", is situated in the Victoria Falls National Park, a UNESCO World Heritage Site. This member of Leading Hotels of the World is one of the celebrated establishments of the world.',
        highlights: [
            'Private path to the Victoria Falls',
            'Historic Edwardian architecture',
            'Famous high tea on the terrace',
            'Spectacular views of the Victoria Falls Bridge',
        ],
        images: {
            thumbnail: '/images/safari/river-aerial.jpg',
            gallery: [
                '/images/safari/wild-dogs.jpg',
            ],
        },
        pricing: {
            currency: 'USD',
            pricePerNightFrom: 450,
            includedInRate: ['Breakfast'],
        },
        roomTypes: [
            {
                id: 'r13',
                name: 'Classic Room',
                description: 'Elegant room with traditional décor and modern amenities.',
                maxOccupancy: 2,
                bedConfiguration: '1 King or 2 Twins',
                amenities: ['Air conditioning', 'Satellite TV', 'Minibar', 'Safe'],
                images: ['/images/safari/dunes-moody.jpg'],
                price: 450,
                available: true,
            }
        ],
        amenities: {
            general: ['Pool', 'Fitness center', 'Business center', 'Library'],
            room: ['Air Conditioning', 'Bathrobe', 'Slippers'],
            dining: ['The Livingstone Room', 'Jungle Junction', 'Stanley’s Terrace'],
            activities: ['Historical tours', 'High tea'],
            services: ['Concierge', '24-hour room service', 'Valet parking'],
        },
        mealPlans: ['Bed & Breakfast', 'Half Board'],
        policies: {
            checkIn: '14:00',
            checkOut: '11:00',
            cancellation: 'Free cancellation up to 7 days before arrival.',
            children: 'All ages welcome.',
            pets: 'No pets allowed.',
        },
        reviews: {
            averageRating: 4.7,
            totalReviews: 1250,
            ratingBreakdown: {
                cleanliness: 4.8,
                service: 4.9,
                location: 5.0,
                value: 4.3,
                facilities: 4.6,
            },
            recentReviews: [],
        },
        features: {
            featured: true,
            popular: true,
        },
        tags: ['Heritage', 'Historic', 'Luxury'],
    },
    {
        id: 'h14',
        slug: 'camp-hwange-hwange',
        name: 'Camp Hwange',
        propertyType: 'eco-lodge',
        starRating: 4,
        location: {
            destination: 'Hwange National Park',
            address: 'Sinamatella area, Hwange National Park',
            coordinates: { lat: -18.65, lng: 26.35 },
            distanceToVictoriaFalls: 200,
            distanceToAirport: 210,
        },
        shortDescription: 'Focusing on the "real" safari experience through walking and game drives.',
        longDescription: 'Camp Hwange is situated in the Sinamatella area of Hwange National Park. The camp is designed to offer a back-to-basics but comfortable safari experience with a heavy emphasis on guiding and walking.',
        highlights: [
            'Exceptional walking safaris',
            'Solar-powered eco-lodge',
            'Waterhole directly in front of camp',
            'Remote and wild location',
        ],
        images: {
            thumbnail: '/images/safari/leopard-tree.jpg',
            gallery: [
                '/images/safari/oryx-dunes.jpg',
            ],
        },
        pricing: {
            currency: 'USD',
            pricePerNightFrom: 380,
            includedInRate: ['All meals', 'Drinks', 'Safari activities'],
        },
        roomTypes: [
            {
                id: 'r14',
                name: 'Thatch & Canvas Suite',
                description: 'Comfortable suite with thatched roof and canvas walls.',
                maxOccupancy: 2,
                bedConfiguration: '1 King or 2 Twins',
                amenities: ['Fan', 'En-suite shower', 'Safe'],
                images: ['/images/safari/oryx-dunes.jpg'],
                price: 380,
                available: true,
            }
        ],
        amenities: {
            general: ['Solar power', 'Lounge', 'Dining tent'],
            room: ['Fan', 'Safe', 'Mosquito net'],
            dining: ['Communal dining', 'Bush breakfasts'],
            activities: ['Walking safaris', 'Game drives', 'Night drives'],
            services: ['Laundry', 'Transfers'],
        },
        mealPlans: ['Fully Inclusive'],
        policies: {
            checkIn: '14:00',
            checkOut: '10:00',
            cancellation: '30 days cancellation.',
            children: '8+ years welcome.',
            pets: 'No.',
        },
        reviews: {
            averageRating: 4.9,
            totalReviews: 24,
            ratingBreakdown: {
                cleanliness: 4.8,
                service: 5.0,
                location: 5.0,
                value: 4.8,
                facilities: 4.7,
            },
            recentReviews: [],
        },
        features: {
            ecoFriendly: true,
        },
        tags: ['Walking', 'Eco', 'Authentic'],
    },
    {
        id: 'h15',
        slug: 'matetsi-victoria-falls',
        name: 'Matetsi Victoria Falls',
        propertyType: 'lodge',
        starRating: 5,
        location: {
            destination: 'Victoria Falls',
            address: 'Matetsi Private Game Reserve, Victoria Falls',
            coordinates: { lat: -17.85, lng: 25.55 },
            distanceToVictoriaFalls: 40,
            distanceToAirport: 55,
        },
        shortDescription: 'Ultra-luxury lodge on the banks of the Zambezi River within an enormous private reserve.',
        longDescription: 'Matetsi Victoria Falls offers a unique combination of safari, river, and falls experiences. It is situated on a private concession with 15km of Zambezi River frontage.',
        highlights: [
            '15km of private river frontage',
            'Ultra-luxury architectural design',
            'Private game reserve exclusivity',
            'Personal butler service',
        ],
        images: {
            thumbnail: '/images/safari/dunes-moody.jpg',
            gallery: [
                '/images/safari/wild-dogs.jpg',
            ],
        },
        pricing: {
            currency: 'USD',
            pricePerNightFrom: 1100,
            includedInRate: ['All meals', 'Premium drinks', 'Private safari', 'Butler service'],
        },
        roomTypes: [
            {
                id: 'r15',
                name: 'River Lodge Suite',
                description: 'Exquisite suite with private plunge pool and river views.',
                maxOccupancy: 2,
                bedConfiguration: '1 King',
                amenities: ['Air conditioning', 'Plunge pool', 'Butler', 'Luxury bath'],
                images: ['/images/safari/elephants-waterhole.jpg'],
                price: 1100,
                available: true,
            }
        ],
        amenities: {
            general: ['Infinity Pool', 'Gym', 'Wine Cellar'],
            room: ['Plunge Pool', 'Outdoor Shower', 'Butler'],
            dining: ['Interactive Kitchen', 'Zambezi Dinner'],
            activities: ['Private Game Drives', 'River Safaris', 'Canoeing'],
            services: ['Private Chef', 'Valet', 'VIP Transfers'],
        },
        mealPlans: ['Fully Inclusive'],
        policies: {
            checkIn: '14:00',
            checkOut: '11:00',
            cancellation: '60 days cancellation.',
            children: 'All ages welcome.',
            pets: 'No.',
        },
        reviews: {
            averageRating: 5.0,
            totalReviews: 35,
            ratingBreakdown: {
                cleanliness: 5.0,
                service: 5.0,
                location: 5.0,
                value: 4.9,
                facilities: 5.0,
            },
            recentReviews: [],
        },
        features: {
            featured: true,
        },
        tags: ['Ultra-Luxury', 'Private Reserve', 'Zambezi'],
    }
];
